on:
  schedule:
    # Runs every day At 1:00.
    - cron:  '0 1 * * *'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan DEMO VSOUSA website
    steps:
      - name: ZAP Scan
        uses: vinisousa/action-full-scan@v0.13.0
        with:
          target: 'https://demo.vsousa.f5latam.app'
